name: Ansible Lint

on: [push, pull_request]

jobs:
  ansible-lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          ./roles/sap_general_preconfigure
          ./roles/sap_netweaver_preconfigure
          ./roles/sap_hana_preconfigure
          ./roles/sap_hana_install
        override-deps: |
          ansible 5.3.0
          ansible-lint==5.3.2
# ansible-core==2.12.1
# Static: use Ansible Community Edition 4.8.0, with lowest compatible Ansible Core 2.11.6 and use Ansible-lint 5.2.1
